version: '3.9'

services:
  web:
    image: redis:7
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${TDL_WS_CONTAINER_NAME}
    environment:
      DEBUG: ${DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
    networks:
      - network
    ports:
      - "8006:8000"
    
  redis:
    image: redis:7
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - network
    ports:
      - "6379:6379"

networks:
  network:
    driver: bridge
